In [1]:
from latent_sim import LatentSim

In [2]:
hub = "/Users/afq/Google Drive/networks/"
ls = LatentSim(hub+'training_water_linear/Poly_1,1',
               "data_files/water_linear_ranges.csv",
              logp=False)

INFO:tensorflow:Restoring parameters from /Users/afq/Google Drive/networks/training_water_linear/Poly_1,1/final_variables


In [3]:
q0 = ls.find_point(T=293.15,p=1.0e5)

[[   293.15003897 100000.00186975    998.20333889  84011.85339362]] [[[ 8.35284692e-01  7.44049592e-01]
  [ 1.51889535e+03 -1.40446744e+03]
  [-1.71556367e-01 -1.54087286e-01]
  [ 3.49693341e+03  3.11237904e+03]]]
[3.89699321e-05 1.86975334e-03] [[ 8.35284692e-01  7.44049592e-01]
 [ 1.51889535e+03 -1.40446744e+03]] [-2.43668113e-05 -2.50207887e-05]
[[   293.15       100000.            998.20334693  84011.69031032]] [[[ 8.35284692e-01  7.44049592e-01]
  [ 1.51889535e+03 -1.40446744e+03]
  [-1.71556367e-01 -1.54087286e-01]
  [ 3.49693341e+03  3.11237904e+03]]]
[0. 0.] [[ 8.35284692e-01  7.44049592e-01]
 [ 1.51889535e+03 -1.40446744e+03]] [0. 0.]
Found point at  [[   293.15       100000.            998.20334693  84011.69031032]]  after  1  iterations.


In [4]:
import numpy as np

In [5]:
ls.encode( np.expand_dims( ls.scale[0,:] , 0) )

array([[-0.10010417,  0.01799381]])

In [6]:
ls.scale

array([[   293.15      , 100000.        ,    998.20334726,
         84011.66779864],
       [   292.15      ,  99000.        ,    997.9935796 ,
         79825.70752921],
       [   294.15      , 101000.        ,    998.40689501,
         88197.20467767]])